# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    config.vm.hostname = "webserver"
    config.vm.define "webserver"
    config.vm.box = "generic/debian10"
    config.vm.network :public_network, ip: "192.168.100.200"
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.name = "webserver"
        vb.memory = 1024
        vb.cpus = 1
    end

    config.vm.provision :ansible do |ansible|
        ansible.inventory_path = "provisioning/inventory/hosts.yml"
        ansible.playbook = "provisioning/site.yml"
    end

end 